# Generated by Django 5.2.4 on 2025-07-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_user_type_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_ons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
